dnevnik_com/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('schedule', include('schedule.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = "dnevnik_com.views.page_404"

main/urls.py
from django.urls import path
from main.views import *


app_name = 'main'

urlpatterns = [
    path('', index, name='main'),
    path('about', about, name='about'),
    path('support', support, name='support'),
    path('for-partners', for_partners, name='for_partners'),
    path('login', log_in, name='login'),
    path('logout/', log_out, name='logout'),
    path('sign-up', sign_up, name='sign_up'),
    path('profile', profile, name='profile'),
    path('join-oo', join_oo, name='join_oo'),
    path('my-marks/<str:period>', my_marks, name='my_marks'),
    path('change-marks/<str:edu_class>/<str:period>', change_marks, name='change-marks'),
    path('mark-back', mark_back, name='mark-back'),
    path('wt-back', wt_back, name='wt-back'),
    path('recovery', recovery, name='recovery'),
]

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField(label='Логин', label_suffix=':')
    password = forms.CharField(widget=forms.PasswordInput, label='Пароль', label_suffix=':')


class RegisterForm(UserCreationForm):
    name = forms.CharField()
    surname = forms.CharField()
    role = forms.ChoiceField(choices=[(0, 'Ученик'), (1, 'Учитель')])
    city = forms.CharField()
    organization = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'name', 'surname', 'role', 'city', 'organization')

main/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http.response import JsonResponse

from .models import *
from .forms import LoginForm, RegisterForm
from . import utils
from .models import Subject, Class, Mark, TeacherProfile, StudentProfile, WorkingPlan


def page_404(request):
    return render(request, '404.html', status=404)


def index(request):
    context = {}
    return render(request, 'main/index.html', context=context)


def about(request):
    context = {}
    return render(request, 'main/about.html', context=context)


def support(request):
    context = {}
    return render(request, 'main/support.html', context=context)


def for_partners(request):
    context = {}
    return render(request, 'main/for_partners.html', context=context)


@login_required(login_url='/login')
def profile(request):
    context = {}
    if request.method == 'GET':
        try:
            student_profile = StudentProfile.objects.get(user=request.user)
            context = {
                'student': student_profile
            }
        except StudentProfile.DoesNotExist:
            try:
                teacher_profile = TeacherProfile.objects.get(user=request.user)
                context = {
                    'teacher': teacher_profile,
                    'classes': teacher_profile.classes.all()
                }
            except TeacherProfile.DoesNotExist:
                return render(request, '404.html')
    return render(request, 'main/profile.html', context=context)


def log_in(request):
    if request.user.is_authenticated:
        return redirect('profile')
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    login(request, user)
                    return redirect('main:profile')
                else:
                    login_form.add_error('__all__', 'Ошибка! Пользователь неактивен!')
            else:
                login_form.add_error('__all__', 'Ошибка! Проверьте введённые данные!')
    else:
        login_form = LoginForm()
    context = {
        'form': login_form,
    }
    return render(request, 'main/login.html', context=context)


def log_out(request):
    logout(request)
    return redirect('/login')


def sign_up(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            name = form.cleaned_data['name']
            surname = form.cleaned_data['surname']
            role = form.cleaned_data['role']
            city = form.cleaned_data['city']
            organization = form.cleaned_data['organization']
            StudentProfile.objects.create(
                user=user,
                name=name,
                surname=surname,
                city=city,
                role=role,
                organization=organization
            )
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/')
    else:
        form = RegisterForm()
    context = {
        'form': form,
    }
    return render(request, 'main/sign_up.html', context=context)


@login_required(login_url='/login')
def my_marks(request, period=''):
    try:
        user_profile = StudentProfile.objects.get(user=request.user)
    except:
        return redirect('/')
    if user_profile:
        if period not in (f'{i}' for i in range(1, 5 + 1)):
            period = utils.get_quarter()
            return redirect(reverse('main:my_marks', args=(period,)))
        subjects = Subject.objects.all()
        if period == '5':
            marks_info = [(subject, [FinalMark.objects.filter(student=user_profile, subject=subject, quarter=str(i)) for i in range(1, 5 + 1)]) for subject in subjects]
        else:
            marks_info = user_profile.get_marks_info(period)
        context = {
            'period': period,
            'subjects': subjects,
            'student': user_profile,
            'marks_info': marks_info,
        }
        return render(request, 'main/my_marks.html', context=context)


@login_required(login_url='/login')
def change_marks(request, edu_class='', period=''):
    teacher_profile = TeacherProfile.objects.get(user=request.user)
    if teacher_profile:
        classes = teacher_profile.classes.all()
        if len(classes) > 0:
            quarter = utils.get_quarter()
            if not edu_class:
                return redirect(
                    reverse('main:change-marks', args=(teacher_profile.classes.all()[0].full_class, quarter)))
            if period not in (f'{i}' for i in range(1, 5 + 1)):
                period = quarter
                return redirect(reverse('main:change-marks', args=(edu_class, period)))
        else:
            return redirect('main:profile')

        context = {
            'teacher': teacher_profile,
            'edu_class': edu_class,
            'period': period,
            'now_year': datetime.datetime.now().year,
            'months': [],
            'students': []
        }
        context = utils.get_previous_context(context, Class)

        # обработка POST запросов
        if request.method == 'POST':
            subject = request.POST.get('select-subject')
            if subject:
                context['subject'] = Subject.objects.get(name=subject)

        context['marks'] = Mark.objects.filter(subject=context['subject'], student__edu_class=context['class_obj'])
        context['work_plans'] = WorkingPlan.objects.filter(subject=context['subject'],
                                                           edu_class=context['class_obj'])

        context = utils.get_months_info(context, WorkingPlan)

        # достаем все оценки всех студентов
        context = utils.get_students_info(context, Mark, StudentProfile)

        return render(request, 'main/change_marks.html', context=context)


def mark_back(request):
    if request.method == 'POST':
        action = request.POST.get('action')
        if action in ('add', 'change', 'delete'):
            new_value = request.POST.get('new_value', None)
            new_comment = request.POST.get('new_comment', None)
            if action == 'add':
                subject = request.POST.get('subject', None)
                edu_class = request.POST.get('edu_class', None)
                mark_date = request.POST.get('mark_date', None)
                student_id = request.POST.get('student_id', None)
                if new_value and new_comment and subject and edu_class and mark_date and student_id:
                    work_type = request.POST.get('work_type', None)
                    mark_date = datetime.date.fromordinal(int(mark_date))
                    if not work_type:
                        work_type = 'ОТВ'
                        class_letter = edu_class[-1]
                        class_number = edu_class[:len(edu_class) - 1]
                        WorkingPlan.objects.get_or_create(
                            edu_class=Class.objects.get(number=class_number, letter=class_letter),
                            subject=Subject.objects.get(name=subject),
                            work_type=work_type,
                            date=mark_date
                        )
                    Mark.objects.get_or_create(
                        student=StudentProfile.objects.get(id=student_id),
                        subject=Subject.objects.get(name=subject),
                        mark=new_value,
                        comment=new_comment,
                        date=mark_date,
                        work_type=work_type
                    )
                    return JsonResponse({'success': True})
            mark_id = request.POST.get('mark_id', None)
            if mark_id:
                mark = Mark.objects.get(id=int(mark_id))
                if action == 'change':
                    if new_value and new_comment:
                        mark.mark = new_value
                        mark.comment = new_comment
                        mark.save()
                else:
                    mark.delete()
                return JsonResponse({'success': True})
        return JsonResponse({'success': False, 'msg': 'Ошибка, проверьте введенные данные.'})


def wt_back(request):
    if request.method == 'POST':
        action = request.POST.get('action')
        if action in ('add', 'change', 'delete'):
            plan_id = request.POST.get('plan_id')
            new_wt = request.POST.get('new_wt')
            new_plan_text = request.POST.get('new_plan_text')
            if plan_id and new_wt and new_plan_text:
                wp = WorkingPlan.objects.get(id=plan_id)
                maybe_wp = WorkingPlan.objects.filter(work_type=new_wt, date=wp.date)
                if not maybe_wp:
                    attached_mark = Mark.objects.filter(work_type=wp.work_type, date=wp.date)[0]
                    wp.work_type = new_wt
                    wp.plan_text = new_plan_text
                    wp.save()
                    attached_mark.work_type = new_wt
                    attached_mark.save()
                    return JsonResponse({'success': True})

templates/main/about.html
{% extends 'base.html' %}
{% load static %}


{% block title %}О сервисе{% endblock %}

{% block profile_button %}
    <a href="{% url 'main:profile' %}" id="login" title="Профиль"
       class="button button_blue button_padding-20    " onclick="" data-category="" data-action=""
       data-target="">
        Профиль
    </a>
{% endblock %}

{% block style %}
    <style>
        .about {
            margin: 0;
            position: absolute;
            top: 45%;
            left: 50%;
            margin-right: -50%;
            transform: translate(-50%, -50%)
        }
    </style>
{% endblock %}

{% block content %}
    <div class="about">
        <h1>О сервисе...</h1>
    </div>
{% endblock %}


templates/main/diary.html
{% extends 'base.html' %}


{% block title %}Главная{% endblock %}

{% block profile_button %}
    <a href="{% url 'main:profile' %}" id="login" title="Профиль"
       class="button button_blue button_padding-20    " onclick="" data-category="" data-action=""
       data-target="">
        Профиль
    </a>
{% endblock %}

{% block style %}
{% endblock %}

{% block content %}

{% endblock %}


templates/main/for_partners.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Партнёрам{% endblock %}

{% block profile_button %}
    <a href="{% url 'main:profile' %}" id="login" title="Профиль"
       class="button button_blue button_padding-20    " onclick="" data-category="" data-action=""
       data-target="">
        Профиль
    </a>
{% endblock %}

{% block style %}
    <style>
        .for-partners {
            margin: 0;
            position: absolute;
            top: 45%;
            left: 50%;
            margin-right: -50%;
            transform: translate(-50%, -50%)
        }
    </style>
{% endblock %}

{% block content %}
    <div class="for-partners">
        <h1>Что-то для них...</h1>
    </div>
{% endblock %}


templates/main/index.html
{% extends 'base.html' %}


{% block title %}Главная{% endblock %}

{% block profile_button %}
    <a href="{% url 'main:profile' %}" id="login" title="Профиль"
       class="button button_blue button_padding-20    " onclick="" data-category="" data-action=""
       data-target="">
        Профиль
    </a>
{% endblock %}

{% block style %}
    <style>
        h2 {
            position: absolute;
            top: 45%;
            left: 50%;
            margin: 0 -50% 0 0;
            transform: translate(-50%, -50%)
        }
    </style>
{% endblock %}

{% block content %}
    <h2>Прототип образовательного сервиса</h2>
{% endblock %}


templates/main/join_oo.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Подключение ОО{% endblock %}

{% block profile_button %}
    <a href="{% url 'main:profile' %}" id="login" title="Профиль"
       class="button button_blue button_padding-20    " onclick="" data-category="" data-action=""
       data-target="">
        Профиль
    </a>
{% endblock %}

{% block style %}
    <style>
        .join {
            text-align: center;
            margin: 0;
            position: absolute;
            top: 45%;
            left: 50%;
            margin-right: -50%;
            transform: translate(-50%, -50%)
        }
    </style>
{% endblock %}

{% block content %}
    <div class="join">
        <h1>Подключение образовательной организации</h1>
        <p>Для того чтобы узнать о правилах подключения, ответьте на несколько вопросов</p>
    </div>
{% endblock %}


templates/main/login.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Авторизация{% endblock %}

{% block style %}
    <style>
        h1 {
            text-align: center;
            margin-bottom: 30px;
        }
        .login {
            margin: 0;
            position: absolute;
            top: 45%;
            left: 50%;
            margin-right: -50%;
            transform: translate(-50%, -50%);
        }
        #id_username {
            margin-left: 12px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="login">
        <h1>Авторизация</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Войти</button>
            <a href="{% url 'main:recovery' %}" style="position: absolute; right: 0;">Забыли пароль?</a>
{#            <a href="{% url 'join_oo' %}" style="position: absolute; right: 5%;">Регистрация</a>#}
        </form>
    </div>
{% endblock %}


templates/main/my_marks.html
{% extends 'base.html' %}
{% load static %}
{% load rounding %}


{% block title %}Мои оценки{% endblock %}

{% block profile_button %}
    <a href="{% url 'main:profile' %}" id="login" title="Профиль"
       class="button button_blue button_padding-20    " onclick="" data-category="" data-action=""
       data-target="">
        Профиль
    </a>
{% endblock %}

{% block style %}
<style>
    .student-marks {
        margin: 0;
        position: absolute;
        top: 32%;
        left: 50%;
        margin-right: -50%;
        transform: translate(-50%, -50%)
    }
    .student {
        padding-bottom: 20px;
        font-size: 19px;
    }
    #period-{{ period }} {
        color: white;
        background: #25aac7;
        padding: 3px 6px;
    }
    .marks-table {
        border: 1px solid black;
        border-collapse: collapse;
        padding: 10px 5px;
        font-size: 17px;
    }
    td {
        padding: 6px 25px;
        border: 1px solid black;
    }
    #mark-list {
        {#display: flex;#}
        width: 400px;
        padding: 10px;
        {#letter-spacing: 10px;#}
    }
    .mark {
        margin: 0 3px;
        font-size: 20px;
        color: white;
        width: 30px;
        padding: 3px 6px 3px 6px;
    }
    #mark-2 {
        background: crimson;
    }
    #mark-3 {
        background: coral;
    }
    #mark-4 {
        background: orange;
    }
    #mark-5 {
        background: #18a230;
    }
    #mark-П {
        background: crimson;
    }
    #mark-Б {
        background: crimson;
    }
</style>
{% endblock %}

{% block content %}
    <div class="student-marks" style="text-align: center;">
        <h1>Мои оценки</h1>
        <div class="student">
            <span id="fio">{{ student.name }} {{ student.surname }}</span>
            <span id="class">{{ student.edu_class }}</span><br>
        </div>
        <a href="{% url 'main:my_marks' '1' %} " id="period-1">1 четверть</a>
        <a href="{% url 'main:my_marks' '2' %} " id="period-2">2 четверть</a>
        <a href="{% url 'main:my_marks' '3' %} " id="period-3">3 четверть</a>
        <a href="{% url 'main:my_marks' '4' %} " id="period-4">4 четверть</a>
        <a href="{% url 'main:my_marks' '0' %} " id="period-5">Итоговые</a>
        {% if period == '5' %}
            <table class="marks-table" style="margin-top: 20px;">
                <tr>
                    <td>№</td>
                    <td>Предмет</td>
                    <td>1 чтв</td>
                    <td>2 чтв</td>
                    <td>3 чтв</td>
                    <td>4 чтв</td>
                    <td>Год</td>
                </tr>
                {% for subject, marks in marks_info %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ subject }}</td>
                        {% for mark in marks %}
                            <td>
                                <span class="mark" id="mark-{{ mark.0.mark }}">{{ mark.0.mark }}</span>
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            <table class="marks-table" style="margin-top: 20px;">
                <tr>
                    <td>№</td>
                    <td>Предмет</td>
                    <td>Оценки</td>
                    <td>Пропуски</td> {# добавить всего/по болезни #}
                    <td>Средний балл</td>
                    <td>{{ period }} четверть<br>Итог</td>
                </tr>
                {% for subject, marks, avg_mark, itog in marks_info %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ subject }}</td>
                        <td id="mark-list">
                            {% for mark in marks %}
                                <span class="mark" id="mark-{{ mark.mark }}">{{ mark.mark }}</span>
                            {% endfor %}
                        </td>
                        <td></td> {# пропуски #}
                        <td><span style="font-size: 20px;">{{ avg_mark }}</span></td>
                        <td><span style="font-size: 20px;">{{ itog.mark }}</span></td> {# итог/четв #}
                    </tr>
                {% endfor %}
            </table>
        {% endif %}
    </div>
{% endblock %}


templates/main/profile.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Профиль{% endblock %}

{% block profile_button %}
    <a href="{% url 'main:logout' %}" id="logout" title="Выйти"
       class="button button_blue button_padding-20    " onclick="" data-category="" data-action=""
       data-target="">
        Выйти
    </a>
{% endblock %}

{% block style %}
    <style>
        .student-info, .teacher-info {
            position: absolute;
            top: 45%;
            left: 30%;
            margin: 0 -50% 0 0;
            transform: translate(-50%, -50%)
        }

        img {
            position: absolute;
            top: 40%;
            left: 45%;
            margin: 0 -50% 0 0;
            transform: translate(-50%, -50%)
        }
    </style>
{% endblock %}

{% block content %}
    {% if student %}
        <div class="student-info">
            <h1>Ученик</h1>
            <p>ФИО: {{ student }}</p>
            <p>Школа: {{ student.school.school_type }} "{{ student.school.school_name }}"</p>
            <p>Город: {{ student.school.city }}</p>
            <p>Класс: {{ student.edu_class }}</p>
            <p>Телефон: {{ student.phone }}</p>
            <p>E-mail: {{ student.email }}</p>
            <a href="{% url 'main:my_marks' 'period' %}" id="my-marks">
                <button id="my-marks-button">Мои оценки</button>
            </a>
            <a href="{% url 'schedule:schedule' %}" id="schedule">
                <button id="schedule-button">Расписание</button>
            </a>
        </div>
        <img src="{{ student.photo.url }}" alt="Фото" style="height: 150px; width: 150px;">
    {% elif teacher %}
        <div class="teacher-info">
            <h1>Преподаватель</h1>
            <p>ФИО: {{ teacher }}</p>
            <p>Школа: {{ teacher.school.school_type }} "{{ teacher.school.school_name }}"</p>
            <p>Город: {{ teacher.school.city }}</p>
            <p>Телефон: {{ teacher.phone }}</p>
            <p>E-mail: {{ teacher.email }}</p>
            <p>Мои классы:</p>
            {% if classes %}
                {% for class in classes %}
                    <a href="{% url 'main:change-marks' class 'period' %}" id="my-marks">{{ class }}</a>
                {% endfor %}
            {% else %}
                <p>Вы не управляете ни 1 классом.</p>
            {% endif %}
        </div>
        <img src="{{ teacher.photo.url }}" alt="Фото" style="height: 150px; width: 150px;">
    {% else %}
        <h1>Ошибка поиска пользователя</h1>
    {% endif %}
{% endblock %}


templates/main/recovery.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Подключение ОО{% endblock %}

{% block profile_button %}
    <a href="{% url 'main:profile' %}" id="login" title="Профиль"
       class="button button_blue button_padding-20    " onclick="" data-category="" data-action=""
       data-target="">
        Профиль
    </a>
{% endblock %}

{% block style %}
    <style>
        .join {
            text-align: center;
            margin: 0;
            position: absolute;
            top: 45%;
            left: 50%;
            margin-right: -50%;
            transform: translate(-50%, -50%)
        }
    </style>
{% endblock %}

{% block content %}
    <div class="join">
        <h1>Восстановление доступа</h1>
    </div>
{% endblock %}


templates/main/sign_up.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Регистрация{% endblock %}

{% block profile_button %}
    <a href="{% url 'main:profile' %}" id="login" title="Профиль"
       class="button button_blue button_padding-20    " onclick="" data-category="" data-action=""
       data-target="">
        Профиль
    </a>
{% endblock %}

{% block style %}
    <style>
        #reg {
            text-align: center;
        }
        .sign-up {
            margin: 0;
            position: absolute;
            top: 45%;
            left: 50%;
            margin-right: -50%;
            transform: translate(-50%, -50%)
        }
    </style>
{% endblock %}

{% block content %}
    <div class="sign-up">
        <h1 id="reg">Регистрация</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Регистрация</button>
        </form>
    </div>
{% endblock %}


templates/main/support.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Поддержка{% endblock %}

{% block profile_button %}
    <a href="{% url 'main:profile' %}" id="login" title="Профиль"
       class="button button_blue button_padding-20    " onclick="" data-category="" data-action=""
       data-target="">
        Профиль
    </a>
{% endblock %}

{% block style %}
    <style>
        .help {
            margin: 0;
            position: absolute;
            top: 45%;
            left: 50%;
            margin-right: -50%;
            transform: translate(-50%, -50%)
        }
    </style>
{% endblock %}

{% block content %}
    <div class="help">
        <h1>Call me by your name</h1>
    </div>
{% endblock %}
