dnevnik_com/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('schedule', include('schedule.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = "dnevnik_com.views.page_404"

main/urls.py
from django.urls import path
from main.views import *


app_name = 'main'

urlpatterns = [
    path('', index, name='main'),
    path('about', about, name='about'),
    path('support', support, name='support'),
    path('for-partners', for_partners, name='for_partners'),
    path('login', log_in, name='login'),
    path('logout/', log_out, name='logout'),
    path('sign-up', sign_up, name='sign_up'),
    path('profile', profile, name='profile'),
    path('join-oo', join_oo, name='join_oo'),
    path('my-marks/<str:period>', my_marks, name='my_marks'),
    path('change-marks/<str:edu_class>/<str:period>', change_marks, name='change-marks'),
    path('mark-back', mark_back, name='mark-back'),
    path('wt-back', wt_back, name='wt-back'),
    path('recovery', recovery, name='recovery'),
]

templates/schedule/schedule.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Расписание{% endblock %}

{% block profile_button %}
    <a href="{% url 'main:profile' %}" id="login" title="Профиль"
       class="button button_blue button_padding-20" onclick="" data-category="" data-action=""
       data-target="">
        Профиль
    </a>
{% endblock %}

{% block style %}
    <style>
        .wd-1, .wd-2, .wd-3 {
            margin-bottom: 30px;
        }
    </style>
{% endblock %}

{% block content %}
    {% for wd, day_lessons, day in lessons %}
        <div class="wd-{{ forloop.counter }}">
            <p>{{ wd }}, {{ day }}</p>
            {% for lesson in day_lessons %}
                <div>
                    <div>
                        <p>{{ lesson.subject }}</p>
                        <p>{{ lesson.lesson_num }}</p>
                    </div>
                    <p>mark</p> {# добавить оценку #}
                    <p>dz</p> {# добавить ДЗ #}
                </div>
            {% endfor %}
        </div>
    {% endfor %}
{% endblock %}